;; automatically generated by unixstyle-install
(module config (lib "configtab.ss" "setup")
  (define doc-dir "/p/advda/elisp/doctool/mzscheme//share/plt/doc")
  (define lib-dir "/p/advda/elisp/doctool/mzscheme//lib/plt")
  (define include-dir "/p/advda/elisp/doctool/mzscheme//include/plt")
  (define bin-dir "/p/advda/elisp/doctool/mzscheme//bin")
  (define absolute-installation? #t))
